#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/s/.Xmodmap"
xrdb -load ~/.Xdefaults
# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &

# wmnd &



# wmsmixer -w &
# idesk &
conky &
skypetab-ng &
#wmbubble &
#wmmatrix &
wmnd -i eth0 &
wmnd -i wlan0 &
kteatime &
gnome-sound-applet &
#http://askubuntu.com/questions/37954/detect-internet-connection
wmnetmon -t 10 -y 2 -r 2 &

#wally &

#wmnd -i wlan0 &
wmbattery &
#wmcube &
#wmspaceweather &
#avant-window-navigator &


#Si usa wicd
#wicd-client &

#O si usa network-admin
nm-applet &

#consolas: acordarse que la consolas cambian (y mejran) si hay algun gtk levantado como gnome-panel. gnome-terinal creo que mantiene los valores despues de que gnome-panel se cierra
#terminator &
#gnome-terminal &
#fbpager -l top &

fbsetbg -l

#xfe &

wmmon &
diodon &

#cpu
wmtop &

#memoria con tema azul para distinguirlo
wmtop -m -a 5 &

wmclockmon &
wmmemload &
wmget &
wmifinfo &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

dropbox start &

#terminator &

#google-chrome &

#evolution &

nuvola-player &
xcompmgr -c -t-5 -l-5 -r4.2 -o.55 &

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/s/.fluxbox/log"
